-- Generated by supabase/scripts/generate-seed.ts — do not edit by hand.
-- Reference date: 2026-08-29 · demo password: tucked-demo

set search_path = public, extensions;

-- demo auth users
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current)
values ('00000000-0000-0000-0000-000000000000', '90000000-0000-4000-8000-000000000001', 'authenticated', 'authenticated', 'supervisor@mapleleaf.example', extensions.crypt('tucked-demo', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '');
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '90000000-0000-4000-8000-000000000001', '90000000-0000-4000-8000-000000000001', 'email', '{"sub":"90000000-0000-4000-8000-000000000001","email":"supervisor@mapleleaf.example"}', now(), now(), now());
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current)
values ('00000000-0000-0000-0000-000000000000', '90000000-0000-4000-8000-000000000002', 'authenticated', 'authenticated', 'educator@mapleleaf.example', extensions.crypt('tucked-demo', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '');
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '90000000-0000-4000-8000-000000000002', '90000000-0000-4000-8000-000000000002', 'email', '{"sub":"90000000-0000-4000-8000-000000000002","email":"educator@mapleleaf.example"}', now(), now(), now());
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current)
values ('00000000-0000-0000-0000-000000000000', '90000000-0000-4000-8000-000000000003', 'authenticated', 'authenticated', 'parent@mapleleaf.example', extensions.crypt('tucked-demo', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '');
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '90000000-0000-4000-8000-000000000003', '90000000-0000-4000-8000-000000000003', 'email', '{"sub":"90000000-0000-4000-8000-000000000003","email":"parent@mapleleaf.example"}', now(), now(), now());

-- tenancy
insert into public.licensee (id, legal_name) values ('00000000-0000-4000-8000-000000000001', 'Maple Leaf Early Learning Inc.');
insert into public.centre (id, licensee_id, name, licence_number, province, timezone, address, service_system_manager, cwelcc_enrolled, opens_at, closes_at)
values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'Maple Leaf Early Learning', 'DEMO-2026-0001', 'ON', 'America/Toronto', '120 Carlton Street, Toronto, ON M5A 4K2', 'Toronto Children’s Services', true, '07:30', '18:00');
insert into public.age_group (id, centre_id, preset, licensed_capacity) values ('00000000-0000-4000-8000-000000000021', '00000000-0000-4000-8000-000000000002', 'infant', 10);
insert into public.age_group (id, centre_id, preset, licensed_capacity) values ('00000000-0000-4000-8000-000000000069', '00000000-0000-4000-8000-000000000002', 'toddler', 15);
insert into public.age_group (id, centre_id, preset, licensed_capacity) values ('00000000-0000-4000-8000-000000000138', '00000000-0000-4000-8000-000000000002', 'preschool', 15);
insert into public.room (id, centre_id, age_group_id, name) values ('00000000-0000-4000-8000-000000000022', '00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000021', 'Infant room');
insert into public.room (id, centre_id, age_group_id, name) values ('00000000-0000-4000-8000-000000000070', '00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000069', 'Toddler room');
insert into public.room (id, centre_id, age_group_id, name) values ('00000000-0000-4000-8000-000000000139', '00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000138', 'Preschool room');

-- people
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000003', '90000000-0000-4000-8000-000000000001', 'Beatrice Alvares', 'supervisor@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000005', '90000000-0000-4000-8000-000000000002', 'Dara Ocampo', 'educator@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000007', null, 'Ellis Marchetti', 'ellis.marchetti@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000009', null, 'Farah Iqbal', 'farah.iqbal@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000011', null, 'Gustav Lindqvist', 'gustav.lindqvist@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000013', null, 'Hye-jin Park', 'hye.jin.park@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000015', null, 'Iris Callahan', 'iris.callahan@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000017', null, 'Jonah Weiss', 'jonah.weiss@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000019', null, 'Karin Sedaris', 'karin.sedaris@mapleleaf.example', null);
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000025', '90000000-0000-4000-8000-000000000003', 'Alex Osei', 'parent@mapleleaf.example', '416-555-0101');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000030', null, 'Alex Tremblay', 'alex.tremblay@family.example', '416-555-0102');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000035', null, 'Alex Nguyen', 'alex.nguyen@family.example', '416-555-0103');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000040', null, 'Alex Kaur', 'alex.kaur@family.example', '416-555-0104');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000045', null, 'Alex Rossi', 'alex.rossi@family.example', '416-555-0105');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000050', null, 'Alex Ivanov', 'alex.ivanov@family.example', '416-555-0106');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000055', null, 'Alex Okafor', 'alex.okafor@family.example', '416-555-0107');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000061', null, 'Alex Dubois', 'alex.dubois@family.example', '416-555-0108');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000066', null, 'Alex Sato', 'alex.sato@family.example', '416-555-0109');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000073', null, 'Alex Ahmed', 'alex.ahmed@family.example', '416-555-0110');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000078', null, 'Alex MacLeod', 'alex.macleod@family.example', '416-555-0111');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000083', null, 'Alex Fernandes', 'alex.fernandes@family.example', '416-555-0112');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000088', null, 'Alex Kim', 'alex.kim@family.example', '416-555-0113');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000094', null, 'Alex Bouchard', 'alex.bouchard@family.example', '416-555-0114');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000099', null, 'Alex Singh', 'alex.singh@family.example', '416-555-0115');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000104', null, 'Alex Costa', 'alex.costa@family.example', '416-555-0116');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000109', null, 'Alex Petrov', 'alex.petrov@family.example', '416-555-0117');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000114', null, 'Alex Diallo', 'alex.diallo@family.example', '416-555-0118');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000119', null, 'Alex Roy', 'alex.roy@family.example', '416-555-0119');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000125', null, 'Alex Wong', 'alex.wong@family.example', '416-555-0120');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000130', null, 'Alex Silva', 'alex.silva@family.example', '416-555-0121');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000135', null, 'Alex Byrne', 'alex.byrne@family.example', '416-555-0122');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000142', null, 'Alex Haddad', 'alex.haddad@family.example', '416-555-0123');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000147', null, 'Alex Larsen', 'alex.larsen@family.example', '416-555-0124');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000152', null, 'Alex Moreau', 'alex.moreau@family.example', '416-555-0125');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000158', null, 'Alex Adeyemi', 'alex.adeyemi@family.example', '416-555-0126');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000163', null, 'Alex Chen', 'alex.chen@family.example', '416-555-0127');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000168', null, 'Alex Novak', 'alex.novak@family.example', '416-555-0128');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000173', null, 'Alex Reyes', 'alex.reyes@family.example', '416-555-0129');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000178', null, 'Alex Gagnon', 'alex.gagnon@family.example', '416-555-0130');
insert into public.person (id, auth_user_id, full_name, email, phone) values ('00000000-0000-4000-8000-000000000187', null, 'Jordan Ahmed', 'jordan.coparent@family.example', '647-555-0199');
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000002', 'supervisor', true, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000006', '00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000002', 'rece', true, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000008', '00000000-0000-4000-8000-000000000007', '00000000-0000-4000-8000-000000000002', 'rece', true, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000010', '00000000-0000-4000-8000-000000000009', '00000000-0000-4000-8000-000000000002', 'rece', true, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000012', '00000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-000000000002', 'rece', true, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000014', '00000000-0000-4000-8000-000000000013', '00000000-0000-4000-8000-000000000002', 'rece', true, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000016', '00000000-0000-4000-8000-000000000015', '00000000-0000-4000-8000-000000000002', 'staff', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000018', '00000000-0000-4000-8000-000000000017', '00000000-0000-4000-8000-000000000002', 'student', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000020', '00000000-0000-4000-8000-000000000019', '00000000-0000-4000-8000-000000000002', 'volunteer', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000026', '00000000-0000-4000-8000-000000000025', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000031', '00000000-0000-4000-8000-000000000030', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000036', '00000000-0000-4000-8000-000000000035', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000041', '00000000-0000-4000-8000-000000000040', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000046', '00000000-0000-4000-8000-000000000045', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000051', '00000000-0000-4000-8000-000000000050', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000056', '00000000-0000-4000-8000-000000000055', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000062', '00000000-0000-4000-8000-000000000061', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000067', '00000000-0000-4000-8000-000000000066', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000074', '00000000-0000-4000-8000-000000000073', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000079', '00000000-0000-4000-8000-000000000078', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000084', '00000000-0000-4000-8000-000000000083', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000089', '00000000-0000-4000-8000-000000000088', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000095', '00000000-0000-4000-8000-000000000094', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000100', '00000000-0000-4000-8000-000000000099', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000110', '00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000115', '00000000-0000-4000-8000-000000000114', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000120', '00000000-0000-4000-8000-000000000119', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000126', '00000000-0000-4000-8000-000000000125', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000131', '00000000-0000-4000-8000-000000000130', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000136', '00000000-0000-4000-8000-000000000135', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000143', '00000000-0000-4000-8000-000000000142', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000148', '00000000-0000-4000-8000-000000000147', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000153', '00000000-0000-4000-8000-000000000152', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000159', '00000000-0000-4000-8000-000000000158', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000164', '00000000-0000-4000-8000-000000000163', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000169', '00000000-0000-4000-8000-000000000168', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000174', '00000000-0000-4000-8000-000000000173', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000179', '00000000-0000-4000-8000-000000000178', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);
insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('00000000-0000-4000-8000-000000000188', '00000000-0000-4000-8000-000000000187', '00000000-0000-4000-8000-000000000002', 'family_adult', false, true);

-- staff PINs (demo: 1234 for every workforce member)
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000007', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000009', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000013', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000015', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000017', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));
insert into public.staff_pin (person_id, centre_id, pin_hash) values ('00000000-0000-4000-8000-000000000019', '00000000-0000-4000-8000-000000000002', extensions.crypt('1234', extensions.gen_salt('bf')));

-- families
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-000000000002', 'Osei household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000029', '00000000-0000-4000-8000-000000000002', 'Tremblay household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000034', '00000000-0000-4000-8000-000000000002', 'Nguyen household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000039', '00000000-0000-4000-8000-000000000002', 'Kaur household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000044', '00000000-0000-4000-8000-000000000002', 'Rossi household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000049', '00000000-0000-4000-8000-000000000002', 'Ivanov household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000054', '00000000-0000-4000-8000-000000000002', 'Okafor household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000060', '00000000-0000-4000-8000-000000000002', 'Dubois household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000065', '00000000-0000-4000-8000-000000000002', 'Sato household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000072', '00000000-0000-4000-8000-000000000002', 'Ahmed household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000077', '00000000-0000-4000-8000-000000000002', 'MacLeod household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000082', '00000000-0000-4000-8000-000000000002', 'Fernandes household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000087', '00000000-0000-4000-8000-000000000002', 'Kim household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000093', '00000000-0000-4000-8000-000000000002', 'Bouchard household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000098', '00000000-0000-4000-8000-000000000002', 'Singh household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000002', 'Costa household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000002', 'Petrov household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000113', '00000000-0000-4000-8000-000000000002', 'Diallo household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000118', '00000000-0000-4000-8000-000000000002', 'Roy household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000124', '00000000-0000-4000-8000-000000000002', 'Wong household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000129', '00000000-0000-4000-8000-000000000002', 'Silva household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000134', '00000000-0000-4000-8000-000000000002', 'Byrne household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000141', '00000000-0000-4000-8000-000000000002', 'Haddad household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000146', '00000000-0000-4000-8000-000000000002', 'Larsen household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000151', '00000000-0000-4000-8000-000000000002', 'Moreau household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000157', '00000000-0000-4000-8000-000000000002', 'Adeyemi household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000162', '00000000-0000-4000-8000-000000000002', 'Chen household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000167', '00000000-0000-4000-8000-000000000002', 'Novak household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000172', '00000000-0000-4000-8000-000000000002', 'Reyes household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000177', '00000000-0000-4000-8000-000000000002', 'Gagnon household');
insert into public.household (id, centre_id, name) values ('00000000-0000-4000-8000-000000000189', '00000000-0000-4000-8000-000000000002', 'Ahmed household (second)');
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000023', '00000000-0000-4000-8000-000000000002', 'Maya Osei', '2026-04-01', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000028', '00000000-0000-4000-8000-000000000002', 'Liam Tremblay', '2025-11-02', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000033', '00000000-0000-4000-8000-000000000002', 'Aisha Nguyen', '2025-06-03', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000038', '00000000-0000-4000-8000-000000000002', 'Noah Kaur', '2026-03-04', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000043', '00000000-0000-4000-8000-000000000002', 'Simran Rossi', '2025-10-05', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000048', '00000000-0000-4000-8000-000000000002', 'Ethan Ivanov', '2025-05-06', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000053', '00000000-0000-4000-8000-000000000002', 'Zoe Okafor', '2026-02-07', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000058', '00000000-0000-4000-8000-000000000002', 'Arjun Okafor', '2025-09-08', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000059', '00000000-0000-4000-8000-000000000002', 'Olivia Dubois', '2025-04-09', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000064', '00000000-0000-4000-8000-000000000002', 'Kai Sato', '2026-01-10', '2026-02-01', null, '00000000-0000-4000-8000-000000000022', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000071', '00000000-0000-4000-8000-000000000002', 'Amara Ahmed', '2025-02-01', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000076', '00000000-0000-4000-8000-000000000002', 'Lucas MacLeod', '2024-09-02', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000081', '00000000-0000-4000-8000-000000000002', 'Fatima Fernandes', '2024-04-03', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000086', '00000000-0000-4000-8000-000000000002', 'Theo Kim', '2024-11-04', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000091', '00000000-0000-4000-8000-000000000002', 'Ines Kim', '2024-06-05', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000092', '00000000-0000-4000-8000-000000000002', 'Ravi Bouchard', '2025-01-06', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000097', '00000000-0000-4000-8000-000000000002', 'Clara Singh', '2024-08-07', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000002', 'Dmitri Costa', '2024-03-08', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000002', 'Nia Petrov', '2024-10-09', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000112', '00000000-0000-4000-8000-000000000002', 'Felix Diallo', '2024-05-10', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000117', '00000000-0000-4000-8000-000000000002', 'Hana Roy', '2024-12-11', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000122', '00000000-0000-4000-8000-000000000002', 'Marco Roy', '2024-07-12', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000123', '00000000-0000-4000-8000-000000000002', 'Priya Wong', '2025-02-13', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000128', '00000000-0000-4000-8000-000000000002', 'Owen Silva', '2024-09-14', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000133', '00000000-0000-4000-8000-000000000002', 'Leila Byrne', '2024-04-15', '2026-02-01', null, '00000000-0000-4000-8000-000000000070', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000140', '00000000-0000-4000-8000-000000000002', 'Jasper Haddad', '2024-01-01', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000145', '00000000-0000-4000-8000-000000000002', 'Mei Larsen', '2023-08-02', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000150', '00000000-0000-4000-8000-000000000002', 'Tomas Moreau', '2023-03-03', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000155', '00000000-0000-4000-8000-000000000002', 'Ada Moreau', '2022-10-04', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000156', '00000000-0000-4000-8000-000000000002', 'Kwame Adeyemi', '2022-05-05', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000161', '00000000-0000-4000-8000-000000000002', 'Sofia Chen', '2021-12-06', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000166', '00000000-0000-4000-8000-000000000002', 'Ben Novak', '2024-01-07', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000171', '00000000-0000-4000-8000-000000000002', 'Anika Reyes', '2023-08-08', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000176', '00000000-0000-4000-8000-000000000002', 'Cole Gagnon', '2023-03-09', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000181', '00000000-0000-4000-8000-000000000002', 'Rosa Osei', '2022-10-10', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000182', '00000000-0000-4000-8000-000000000002', 'Ivan Osei', '2022-05-11', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000183', '00000000-0000-4000-8000-000000000002', 'Tara Tremblay', '2021-12-12', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000184', '00000000-0000-4000-8000-000000000002', 'Louis Nguyen', '2024-01-13', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000185', '00000000-0000-4000-8000-000000000002', 'Yuki Kaur', '2023-08-14', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)
values ('00000000-0000-4000-8000-000000000186', '00000000-0000-4000-8000-000000000002', 'Sam Rossi', '2023-03-15', '2026-02-01', null, '00000000-0000-4000-8000-000000000139', false);
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000023', '00000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000028', '00000000-0000-4000-8000-000000000029', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000033', '00000000-0000-4000-8000-000000000034', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000038', '00000000-0000-4000-8000-000000000039', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000043', '00000000-0000-4000-8000-000000000044', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000048', '00000000-0000-4000-8000-000000000049', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000053', '00000000-0000-4000-8000-000000000054', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000058', '00000000-0000-4000-8000-000000000054', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000059', '00000000-0000-4000-8000-000000000060', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000064', '00000000-0000-4000-8000-000000000065', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000071', '00000000-0000-4000-8000-000000000072', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000076', '00000000-0000-4000-8000-000000000077', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000081', '00000000-0000-4000-8000-000000000082', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000086', '00000000-0000-4000-8000-000000000087', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000091', '00000000-0000-4000-8000-000000000087', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000092', '00000000-0000-4000-8000-000000000093', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000097', '00000000-0000-4000-8000-000000000098', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000112', '00000000-0000-4000-8000-000000000113', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000117', '00000000-0000-4000-8000-000000000118', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000122', '00000000-0000-4000-8000-000000000118', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000123', '00000000-0000-4000-8000-000000000124', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000128', '00000000-0000-4000-8000-000000000129', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000133', '00000000-0000-4000-8000-000000000134', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000140', '00000000-0000-4000-8000-000000000141', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000145', '00000000-0000-4000-8000-000000000146', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000150', '00000000-0000-4000-8000-000000000151', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000155', '00000000-0000-4000-8000-000000000151', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000156', '00000000-0000-4000-8000-000000000157', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000161', '00000000-0000-4000-8000-000000000162', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000166', '00000000-0000-4000-8000-000000000167', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000171', '00000000-0000-4000-8000-000000000172', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000176', '00000000-0000-4000-8000-000000000177', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000181', '00000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000182', '00000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000183', '00000000-0000-4000-8000-000000000029', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000184', '00000000-0000-4000-8000-000000000034', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000185', '00000000-0000-4000-8000-000000000039', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000186', '00000000-0000-4000-8000-000000000044', '00000000-0000-4000-8000-000000000002');
insert into public.child_household (child_id, household_id, centre_id) values ('00000000-0000-4000-8000-000000000071', '00000000-0000-4000-8000-000000000189', '00000000-0000-4000-8000-000000000002');
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000027', '00000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-000000000025', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000032', '00000000-0000-4000-8000-000000000029', '00000000-0000-4000-8000-000000000030', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000037', '00000000-0000-4000-8000-000000000034', '00000000-0000-4000-8000-000000000035', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000042', '00000000-0000-4000-8000-000000000039', '00000000-0000-4000-8000-000000000040', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000047', '00000000-0000-4000-8000-000000000044', '00000000-0000-4000-8000-000000000045', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000052', '00000000-0000-4000-8000-000000000049', '00000000-0000-4000-8000-000000000050', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000057', '00000000-0000-4000-8000-000000000054', '00000000-0000-4000-8000-000000000055', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000063', '00000000-0000-4000-8000-000000000060', '00000000-0000-4000-8000-000000000061', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000068', '00000000-0000-4000-8000-000000000065', '00000000-0000-4000-8000-000000000066', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000075', '00000000-0000-4000-8000-000000000072', '00000000-0000-4000-8000-000000000073', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000080', '00000000-0000-4000-8000-000000000077', '00000000-0000-4000-8000-000000000078', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000085', '00000000-0000-4000-8000-000000000082', '00000000-0000-4000-8000-000000000083', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000090', '00000000-0000-4000-8000-000000000087', '00000000-0000-4000-8000-000000000088', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000096', '00000000-0000-4000-8000-000000000093', '00000000-0000-4000-8000-000000000094', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000098', '00000000-0000-4000-8000-000000000099', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000106', '00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000111', '00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000116', '00000000-0000-4000-8000-000000000113', '00000000-0000-4000-8000-000000000114', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000121', '00000000-0000-4000-8000-000000000118', '00000000-0000-4000-8000-000000000119', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000127', '00000000-0000-4000-8000-000000000124', '00000000-0000-4000-8000-000000000125', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000132', '00000000-0000-4000-8000-000000000129', '00000000-0000-4000-8000-000000000130', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000137', '00000000-0000-4000-8000-000000000134', '00000000-0000-4000-8000-000000000135', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000144', '00000000-0000-4000-8000-000000000141', '00000000-0000-4000-8000-000000000142', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000149', '00000000-0000-4000-8000-000000000146', '00000000-0000-4000-8000-000000000147', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000154', '00000000-0000-4000-8000-000000000151', '00000000-0000-4000-8000-000000000152', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000160', '00000000-0000-4000-8000-000000000157', '00000000-0000-4000-8000-000000000158', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000165', '00000000-0000-4000-8000-000000000162', '00000000-0000-4000-8000-000000000163', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000170', '00000000-0000-4000-8000-000000000167', '00000000-0000-4000-8000-000000000168', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000175', '00000000-0000-4000-8000-000000000172', '00000000-0000-4000-8000-000000000173', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000180', '00000000-0000-4000-8000-000000000177', '00000000-0000-4000-8000-000000000178', '00000000-0000-4000-8000-000000000002', 'parent', true, true, true, true, true, null);
insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)
values ('00000000-0000-4000-8000-000000000190', '00000000-0000-4000-8000-000000000189', '00000000-0000-4000-8000-000000000187', '00000000-0000-4000-8000-000000000002', 'parent', true, true, false, false, false, null);
