/**
 * Generates supabase/seed.sql from the Maple Leaf Early Learning fixture
 * (packages/domain) — one source of truth for demo data in tests and the
 * seeded local stack. Run: pnpm db:seed:gen [--date=YYYY-MM-DD]
 *
 * Creates auth users (password: tucked-demo) ONLY for the three demo logins;
 * every other fixture person exists without an account until invited.
 * seed.sql is applied automatically by `supabase db reset`.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMapleLeaf } from '@tucked/domain';

const dateArg = process.argv.find((a) => a.startsWith('--date='))?.slice(7);
const reference = dateArg ? new Date(`${dateArg}T12:00:00Z`) : new Date();
const f = buildMapleLeaf(reference);

const q = (v: string | null): string => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const b = (v: boolean): string => (v ? 'true' : 'false');

const AUTH_ID_PREFIX = '90000000-0000-4000-8000-';
const demoEmails = new Set(Object.values(f.demoLogins));
const authIdFor = new Map<string, string>();
let authN = 0;
for (const p of f.people) {
  if (p.email && demoEmails.has(p.email)) {
    authN += 1;
    authIdFor.set(p.id, `${AUTH_ID_PREFIX}${authN.toString().padStart(12, '0')}`);
  }
}

const lines: string[] = [
  '-- Generated by supabase/scripts/generate-seed.ts — do not edit by hand.',
  `-- Reference date: ${reference.toISOString().slice(0, 10)} · demo password: tucked-demo`,
  '',
  'set search_path = public, extensions;',
  '',
  '-- demo auth users',
];

for (const [personId, authId] of authIdFor) {
  const person = f.people.find((p) => p.id === personId)!;
  lines.push(
    `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current)`,
    `values ('00000000-0000-0000-0000-000000000000', '${authId}', 'authenticated', 'authenticated', ${q(person.email)}, extensions.crypt('tucked-demo', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '');`,
    `insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)`,
    `values (gen_random_uuid(), '${authId}', '${authId}', 'email', '{"sub":"${authId}","email":"${person.email}"}', now(), now(), now());`,
  );
}

lines.push('', '-- tenancy');
lines.push(
  `insert into public.licensee (id, legal_name) values ('${f.licensee.id}', ${q(f.licensee.legalName)});`,
);
const c = f.centre;
lines.push(
  `insert into public.centre (id, licensee_id, name, licence_number, province, timezone, address, service_system_manager, cwelcc_enrolled, opens_at, closes_at)`,
  `values ('${c.id}', '${c.licenseeId}', ${q(c.name)}, ${q(c.licenceNumber)}, '${c.province}', ${q(c.timezone)}, ${q(c.address)}, ${q(c.serviceSystemManager)}, ${b(c.cwelccEnrolled)}, '${c.opensAt}', '${c.closesAt}');`,
);
for (const g of f.ageGroupConfigs) {
  lines.push(
    `insert into public.age_group (id, centre_id, preset, licensed_capacity) values ('${g.id}', '${g.centreId}', '${g.ageGroupId}', ${g.licensedCapacity});`,
  );
}
for (const r of f.rooms) {
  lines.push(
    `insert into public.room (id, centre_id, age_group_id, name) values ('${r.id}', '${r.centreId}', '${r.ageGroupConfigId}', ${q(r.name)});`,
  );
}

lines.push('', '-- people');
for (const p of f.people) {
  const authId = authIdFor.get(p.id) ?? null;
  lines.push(
    `insert into public.person (id, auth_user_id, full_name, email, phone) values ('${p.id}', ${authId ? `'${authId}'` : 'null'}, ${q(p.fullName)}, ${q(p.email)}, ${q(p.phone)});`,
  );
}
for (const r of f.personRoles) {
  lines.push(
    `insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('${r.id}', '${r.personId}', '${r.centreId}', '${r.role}', ${b(r.qualified)}, ${b(r.active)});`,
  );
}

lines.push('', '-- staff PINs (demo: 1234 for every workforce member)');
for (const r of f.personRoles) {
  if (r.role !== 'family_adult') {
    lines.push(
      `insert into public.staff_pin (person_id, centre_id, pin_hash) values ('${r.personId}', '${r.centreId}', extensions.crypt('1234', extensions.gen_salt('bf')));`,
    );
  }
}

lines.push('', '-- families');
for (const h of f.households) {
  lines.push(
    `insert into public.household (id, centre_id, name) values ('${h.id}', '${h.centreId}', ${q(h.name)});`,
  );
}
for (const ch of f.children) {
  lines.push(
    `insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)`,
    `values ('${ch.id}', '${ch.centreId}', ${q(ch.fullName)}, '${ch.dateOfBirth}', '${ch.admissionDate}', ${ch.dischargeDate ? `'${ch.dischargeDate}'` : 'null'}, ${ch.currentRoomId ? `'${ch.currentRoomId}'` : 'null'}, ${b(ch.attendsSchool)});`,
  );
}
for (const link of f.childHouseholds) {
  lines.push(
    `insert into public.child_household (child_id, household_id, centre_id) values ('${link.childId}', '${link.householdId}', '${c.id}');`,
  );
}
for (const m of f.householdMembers) {
  lines.push(
    `insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)`,
    `values ('${m.id}', '${m.householdId}', '${m.personId}', '${c.id}', ${q(m.relationship)}, ${b(m.canView)}, ${b(m.canMessage)}, ${b(m.canPickup)}, ${b(m.canConsent)}, ${b(m.canBill)}, ${m.revokedAt ? q(m.revokedAt) : 'null'});`,
  );
}

// ── demo day: a living centre for the program-advisor walkthrough ───────────
// Direct inserts (service context); rule triggers still run. Times are
// relative to seed time so the demo reads sensibly whenever it is loaded.
const careStaff = f.personRoles.filter((r) =>
  ['supervisor', 'rece', 'staff'].includes(r.role),
);
const supervisor = f.people.find((p) => p.email === f.demoLogins.supervisor)!;
const educator = f.people.find((p) => p.email === f.demoLogins.educator)!;
const demoParent = f.people.find((p) => p.email === f.demoLogins.parent)!;
const roomsById = new Map(f.rooms.map((r) => [r.id, r]));
const cfgById = new Map(f.ageGroupConfigs.map((g) => [g.id, g]));
const infants = f.children.filter(
  (ch) => cfgById.get(roomsById.get(ch.currentRoomId!)!.ageGroupConfigId)!.ageGroupId === 'infant',
);
const demoChildIds = new Set(
  f.childHouseholds
    .filter((l) => {
      const hh = f.households.find((h) => h.id === l.householdId)!;
      return f.householdMembers.some((m) => m.householdId === hh.id && m.personId === demoParent.id);
    })
    .map((l) => l.childId),
);

lines.push('', '-- ── demo day ──────────────────────────────────────────────');

for (const r of careStaff) {
  lines.push(
    `insert into public.staff_shift (centre_id, person_id, room_id, shift_date, in_at, recorded_by) values ('${c.id}', '${r.personId}', '${f.rooms[0]!.id}', current_date, now() - interval '4 hours', '${supervisor.id}');`,
  );
}

f.children.forEach((ch, i) => {
  lines.push(
    `insert into public.attendance_event (centre_id, child_id, room_id, event_type, actual_time, attendance_date, recorded_by) values ('${c.id}', '${ch.id}', '${ch.currentRoomId}', 'arrive', now() - interval '${200 - i} minutes', '1970-01-01', '${educator.id}');`,
  );
});

lines.push(
  `insert into public.care_log (centre_id, child_id, room_id, log_type, logged_at, log_date, payload, recorded_by)`,
  `select '${c.id}', ch.id, ch.current_room_id, 'health_observation', now() - interval '3 hours', '1970-01-01', '{"observation": "settled on arrival"}', '${educator.id}' from public.child ch where ch.centre_id = '${c.id}' limit 5;`,
  `insert into public.care_log (centre_id, child_id, room_id, log_type, logged_at, log_date, payload, recorded_by)`,
  `select '${c.id}', ch.id, ch.current_room_id, 'meal', now() - interval '90 minutes', '1970-01-01', '{"meal": "lunch", "eaten": "most"}', '${educator.id}' from public.child ch where ch.centre_id = '${c.id}';`,
  `insert into public.care_log (centre_id, child_id, room_id, log_type, logged_at, log_date, payload, recorded_by)`,
  `select '${c.id}', ch.id, ch.current_room_id, 'outdoor', now() - interval '2 hours', '1970-01-01', '{"minutes": 90}', '${educator.id}' from public.child ch where ch.centre_id = '${c.id}';`,
);
for (const inf of infants) {
  lines.push(
    `insert into public.care_log (centre_id, child_id, room_id, log_type, logged_at, log_date, payload, recorded_by) values ('${c.id}', '${inf.id}', '${inf.currentRoomId}', 'nap_start', now() - interval '60 minutes', '1970-01-01', '{}', '${educator.id}');`,
    `insert into public.care_log (centre_id, child_id, room_id, log_type, logged_at, log_date, payload, recorded_by) values ('${c.id}', '${inf.id}', '${inf.currentRoomId}', 'sleep_check', now() - interval '45 minutes', '1970-01-01', '{"breathing_ok": true, "position": "back"}', '${educator.id}');`,
    `insert into public.care_log (centre_id, child_id, room_id, log_type, logged_at, log_date, payload, recorded_by) values ('${c.id}', '${inf.id}', '${inf.currentRoomId}', 'sleep_check', now() - interval '30 minutes', '1970-01-01', '{"breathing_ok": true, "position": "back"}', '${educator.id}');`,
  );
}

// The accident lands on a demo-household child so the parent@ login can
// demonstrate the s. 36(4) acknowledge loop end to end.
const accidentChild = f.children.find((ch) => demoChildIds.has(ch.id) && ch.id !== f.children[0]!.id)!;
lines.push(
  `insert into public.accident_report (centre_id, child_id, occurred_at, occurred_date, location, description, injury, severity, first_aid, head_injury, concussion_watch_note, completed_by)`,
  `values ('${c.id}', '${accidentChild.id}', now() - interval '100 minutes', '1970-01-01', 'Playground', 'Tripped on the path and bumped their head on the edge of the planter', 'Small bump above the left eyebrow', 'minor', 'Ice pack for 10 minutes, comforted, observed', true, 'Watch for vomiting, drowsiness or unusual behaviour for 24 hours', '${educator.id}');`,
);

const mayaId = f.children[0]!.id;
lines.push(
  `insert into public.consent (centre_id, child_id, consent_type, purpose, status, granted_by, evidence)`,
  `select '${c.id}', ch, t, 'enrolment', case when t in ('photo_third_party', 'social_media') then 'declined' else 'granted' end, '${demoParent.id}', 'in-app decision'`,
  `from unnest(array[${[...demoChildIds].map((id) => `'${id}'`).join(',')}]::uuid[]) ch, unnest(enum_range(null::public.consent_type)) t;`,
  `select app.ensure_record_items('${c.id}', ch) from unnest(array[${[...demoChildIds].map((id) => `'${id}'`).join(',')}]::uuid[]) ch;`,
  `update public.child_record_item set status = case when item_type = 'discharge' then 'not_applicable'::public.record_item_status else 'provided'::public.record_item_status end,`,
  `  content = case when item_type = 'health_immunisation' then '{"allergies": [], "immunisation": "up to date"}'::jsonb else '{"note": "provided at enrolment"}'::jsonb end,`,
  `  updated_by = '${demoParent.id}', verified_by = '${supervisor.id}', verified_at = now()`,
  `where child_id in (${[...demoChildIds].map((id) => `'${id}'`).join(',')});`,
  `insert into public.pickup_authorisation (centre_id, child_id, person_id) select '${c.id}', ch, '${demoParent.id}' from unnest(array[${[...demoChildIds].map((id) => `'${id}'`).join(',')}]::uuid[]) ch;`,
  `insert into public.medication_authorisation (centre_id, child_id, kind, drug_name, dose, schedule, original_container_checked, storage_instructions, parent_authorised_by, authorisation_evidence, recorded_by)`,
  `values ('${c.id}', '${mayaId}', 'diaper_cream', 'Zinc barrier cream', null, null, true, 'Change table cupboard', '${demoParent.id}', 'blanket consent on enrolment form', '${supervisor.id}');`,
  `insert into public.medication_administration (centre_id, child_id, authorisation_id, administered_at, administered_date, outcome, administered_by)`,
  `select '${c.id}', '${mayaId}', a.id, now() - interval '50 minutes', '1970-01-01', 'applied at change', '${educator.id}' from public.medication_authorisation a where a.child_id = '${mayaId}';`,
);

lines.push('', '-- staff credentials (one VSC expiring soon for the exceptions demo)');
careStaff.forEach((r, i) => {
  lines.push(
    `insert into public.credential (centre_id, person_id, credential_type, issued_on, expires_on, recorded_by) values ('${c.id}', '${r.personId}', 'first_aid_cpr', (current_date - interval '1 year')::date, (current_date + interval '${i === 1 ? '25 days' : '2 years'}')::date, '${supervisor.id}');`,
    `insert into public.credential (centre_id, person_id, credential_type, issued_on, expires_on, recorded_by) values ('${c.id}', '${r.personId}', 'vsc', (current_date - interval '2 years')::date, (current_date + interval '3 years')::date, '${supervisor.id}');`,
  );
});

lines.push(
  '',
  '-- an announcement (quiet, Later channel)',
  `insert into public.announcement (centre_id, title, body, created_by)`,
  `values ('${c.id}', 'Pyjama day on Friday', 'Friday is pyjama day across all rooms — cosy clothes welcome. Outdoor play still happens, so please send weather-appropriate layers too.', '${supervisor.id}');`,
);

lines.push('', '-- stories for the demo family, and one unacknowledged Now alert');
for (const id of demoChildIds) {
  const first = f.children.find((ch) => ch.id === id)!.fullName.split(' ')[0];
  lines.push(
    `insert into public.story (centre_id, child_id, story_date, draft_text, educator_note, published_at, published_by)`,
    `values ('${c.id}', '${id}', current_date, 'We spent time outside today — the leaf pile was a hit. ${first} ate most of lunch and settled well for rest.', 'Lovely day. Ask about the leaf fort.', now(), '${educator.id}');`,
    `insert into public.notification (centre_id, child_id, recipient_person_id, channel, event_type, title, body, created_by)`,
    `values ('${c.id}', '${id}', '${demoParent.id}', 'later', 'story', 'Today''s story', 'The day''s story is ready.', '${educator.id}');`,
  );
}
// (The accident's Now alerts are created by the 0015 database trigger.)

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'seed.sql');
writeFileSync(out, lines.join('\n') + '\n', 'utf8');
console.log(
  `Wrote ${out}: ${f.children.length} children, ${f.people.length} people, ${f.households.length} households, ${authIdFor.size} demo logins.`,
);
