/**
 * Generates supabase/seed.sql from the Maple Leaf Early Learning fixture
 * (packages/domain) — one source of truth for demo data in tests and the
 * seeded local stack. Run: pnpm db:seed:gen [--date=YYYY-MM-DD]
 *
 * Creates auth users (password: tucked-demo) ONLY for the three demo logins;
 * every other fixture person exists without an account until invited.
 * seed.sql is applied automatically by `supabase db reset`.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMapleLeaf } from '@tucked/domain';

const dateArg = process.argv.find((a) => a.startsWith('--date='))?.slice(7);
const reference = dateArg ? new Date(`${dateArg}T12:00:00Z`) : new Date();
const f = buildMapleLeaf(reference);

const q = (v: string | null): string => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const b = (v: boolean): string => (v ? 'true' : 'false');

const AUTH_ID_PREFIX = '90000000-0000-4000-8000-';
const demoEmails = new Set(Object.values(f.demoLogins));
const authIdFor = new Map<string, string>();
let authN = 0;
for (const p of f.people) {
  if (p.email && demoEmails.has(p.email)) {
    authN += 1;
    authIdFor.set(p.id, `${AUTH_ID_PREFIX}${authN.toString().padStart(12, '0')}`);
  }
}

const lines: string[] = [
  '-- Generated by supabase/scripts/generate-seed.ts — do not edit by hand.',
  `-- Reference date: ${reference.toISOString().slice(0, 10)} · demo password: tucked-demo`,
  '',
  'set search_path = public, extensions;',
  '',
  '-- demo auth users',
];

for (const [personId, authId] of authIdFor) {
  const person = f.people.find((p) => p.id === personId)!;
  lines.push(
    `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current)`,
    `values ('00000000-0000-0000-0000-000000000000', '${authId}', 'authenticated', 'authenticated', ${q(person.email)}, extensions.crypt('tucked-demo', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '');`,
    `insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)`,
    `values (gen_random_uuid(), '${authId}', '${authId}', 'email', '{"sub":"${authId}","email":"${person.email}"}', now(), now(), now());`,
  );
}

lines.push('', '-- tenancy');
lines.push(
  `insert into public.licensee (id, legal_name) values ('${f.licensee.id}', ${q(f.licensee.legalName)});`,
);
const c = f.centre;
lines.push(
  `insert into public.centre (id, licensee_id, name, licence_number, province, timezone, address, service_system_manager, cwelcc_enrolled, opens_at, closes_at)`,
  `values ('${c.id}', '${c.licenseeId}', ${q(c.name)}, ${q(c.licenceNumber)}, '${c.province}', ${q(c.timezone)}, ${q(c.address)}, ${q(c.serviceSystemManager)}, ${b(c.cwelccEnrolled)}, '${c.opensAt}', '${c.closesAt}');`,
);
for (const g of f.ageGroupConfigs) {
  lines.push(
    `insert into public.age_group (id, centre_id, preset, licensed_capacity) values ('${g.id}', '${g.centreId}', '${g.ageGroupId}', ${g.licensedCapacity});`,
  );
}
for (const r of f.rooms) {
  lines.push(
    `insert into public.room (id, centre_id, age_group_id, name) values ('${r.id}', '${r.centreId}', '${r.ageGroupConfigId}', ${q(r.name)});`,
  );
}

lines.push('', '-- people');
for (const p of f.people) {
  const authId = authIdFor.get(p.id) ?? null;
  lines.push(
    `insert into public.person (id, auth_user_id, full_name, email, phone) values ('${p.id}', ${authId ? `'${authId}'` : 'null'}, ${q(p.fullName)}, ${q(p.email)}, ${q(p.phone)});`,
  );
}
for (const r of f.personRoles) {
  lines.push(
    `insert into public.person_role (id, person_id, centre_id, role, qualified, active) values ('${r.id}', '${r.personId}', '${r.centreId}', '${r.role}', ${b(r.qualified)}, ${b(r.active)});`,
  );
}

lines.push('', '-- families');
for (const h of f.households) {
  lines.push(
    `insert into public.household (id, centre_id, name) values ('${h.id}', '${h.centreId}', ${q(h.name)});`,
  );
}
for (const ch of f.children) {
  lines.push(
    `insert into public.child (id, centre_id, full_name, date_of_birth, admission_date, discharge_date, current_room_id, attends_school)`,
    `values ('${ch.id}', '${ch.centreId}', ${q(ch.fullName)}, '${ch.dateOfBirth}', '${ch.admissionDate}', ${ch.dischargeDate ? `'${ch.dischargeDate}'` : 'null'}, ${ch.currentRoomId ? `'${ch.currentRoomId}'` : 'null'}, ${b(ch.attendsSchool)});`,
  );
}
for (const link of f.childHouseholds) {
  lines.push(
    `insert into public.child_household (child_id, household_id, centre_id) values ('${link.childId}', '${link.householdId}', '${c.id}');`,
  );
}
for (const m of f.householdMembers) {
  lines.push(
    `insert into public.household_member (id, household_id, person_id, centre_id, relationship, can_view, can_message, can_pickup, can_consent, can_bill, revoked_at)`,
    `values ('${m.id}', '${m.householdId}', '${m.personId}', '${c.id}', ${q(m.relationship)}, ${b(m.canView)}, ${b(m.canMessage)}, ${b(m.canPickup)}, ${b(m.canConsent)}, ${b(m.canBill)}, ${m.revokedAt ? q(m.revokedAt) : 'null'});`,
  );
}

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'seed.sql');
writeFileSync(out, lines.join('\n') + '\n', 'utf8');
console.log(
  `Wrote ${out}: ${f.children.length} children, ${f.people.length} people, ${f.households.length} households, ${authIdFor.size} demo logins.`,
);
